formAhp/urls.py
from django.contrib import admin
from django.urls import path, include
from groups.views import AjaxPostView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # ... the rest of your URLconf goes here ...
    path('admin/', admin.site.urls),
    path('auth/', include('django.contrib.auth.urls')),
    path('', include('criterion.urls', namespace='home')),
    path('criterion/', include('criterion.urls', namespace='criterion')),
    path('user/', include('user.urls', namespace='user')),
    path('groups/', include('groups.urls', namespace='groups')),
    path('research/', include('research.urls', namespace='research')),
    path('ajax-post', AjaxPostView, name='ajax-post'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)







# auth/login/ [name='login']
# auth/logout/ [name='logout']
# auth/password_change/ [name='password_change']
# auth/password_change/done/ [name='password_change_done']
# auth/password_reset/ [name='password_reset']
# auth/password_reset/done/ [name='password_reset_done']
# auth/reset/<uidb64>/<token>/ [name='password_reset_confirm']
# auth/reset/done/ [name='password_reset_complete']

groups/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views


app_name = 'groups'


urlpatterns = [
    path('', views.GroupsList.as_view(), name='list'),
    path('add', views.GroupsCreate.as_view(), name='add'),
    path('detail/<str:pk>/', views.GroupsDetail.as_view(), name='detail'),
    path('update/<str:pk>/', views.GroupsUpdate.as_view(), name='update'),
    path('delete/<str:pk>', views.GroupsDelete.as_view(), name='delete'),
    path('relationship/<str:pk>', views.RelationshipCreate.as_view(), name='relationship'),
    # path('execution/<str:pk>', views.ExecutionView.as_view(), name='execution'),
    path('preview/<str:pk>', views.PublishView.as_view(), name='preview'),
    path('publish/<str:pk>', views.PublishView.as_view(), name='publish'),
]

user/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views


app_name = 'user'


urlpatterns = [
    path('', views.UserList.as_view(), name='list'),
    path('add', views.UserCreate.as_view(), name='add'),
    path('detail/<str:pk>/', views.UserDetail.as_view(), name='detail'),
    path('update/<str:pk>/', views.UserUpdate.as_view(), name='update'),
    path('delete/<str:pk>', views.UserDelete.as_view(), name='delete'),
]

groups/models.py
from django.utils.translation import ugettext_lazy as _
from django.db import models
from django.urls import reverse
import uuid


class BaseModel(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)

    class Meta:
        abstract = True


class Groups(BaseModel):
    name = models.CharField(max_length=200)
    created_by = models.ForeignKey(
        'user.User', 
        on_delete=models.PROTECT, 
        verbose_name=_("Criado por"),
        related_name='user_created_by'        
    )
    created_at = models.DateTimeField(auto_now_add=True,  null=True)
    updated_at = models.DateTimeField(auto_now=True)
    published = models.BooleanField(default=False)

    def get_absolute_url(self):
        return reverse('groups:detail', kwargs={'pk': self.pk})

    def relations_count(self):
        a = GroupRelationship.objects.filter(group=self.id).count()
        return a

    def amount_questions(self):
        sum = 0
        for i in range(1,self.relations_count()):
            sum += i
        return sum

    def __str__(self):
        return self.name

class GroupRelationship(BaseModel):
    group = models.ForeignKey(
        'groups.Groups', 
        on_delete=models.PROTECT, 
        verbose_name=_("Grupo"),
    )
    criterion = models.ForeignKey(
        'criterion.Criterion', 
        on_delete=models.PROTECT, 
        verbose_name=_("Critério"),
    )

    def get_absolute_url(self):
        return reverse('groups:groups', kwargs={'pk': self.pk})
    
    def __str__(self):
        return self.criterion.name

groups/views.py
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.contrib.auth.decorators import login_required
from django.views.generic import DetailView, ListView
from django.utils.decorators import method_decorator
from django.urls import reverse_lazy
from django.http import Http404

from groups.models import Groups, GroupRelationship
from criterion.models import Criterion


from django.views.generic import TemplateView





class GroupsList(ListView):
    model = Groups

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get_queryset(self):
        context = Groups.objects.filter(created_by=self.request.user)
        return context


class GroupsDetail(DetailView):
    model = Groups
    http_method_names = ['get', 'post']

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        data['criterion_list'] = Criterion.objects.filter(created_by=self.request.user)
        data['relations_list'] = GroupRelationship.objects.filter(group=self.object)
        return data


import numpy as np 


class PublishView(DetailView):
    template_name = 'groups/groups_publish.html'	
    model = Groups
    http_method_names = ['get', 'post']
    quant_crit = None
    criterions = []

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        data['criterion_list'] = Criterion.objects.filter(created_by=self.request.user)
        items = GroupRelationship.objects.filter(group=self.object)
        self.criterions = []
        for el in items:
            self.criterions.append(el.criterion.name)
        data['relations_list'] = [[items[i].criterion.name,items[j].criterion.name] for i in range(len(items)) for j in range(i+1, len(items))]
        data['len_relations'] = self.object.amount_questions()
        data['objects'] = self.object
        data['id'] = self.object.id
        data['len_criterios'] = self.object.relations_count()
        return data

    def post(self, request, *args, **kwargs):
        print(request.POST)
        processPost(request.POST, self.criterions)



# def relations_values(i):
#     from_for = {
#         '0':9,
#         '1':6,
#         '2':3,
#         '3':1,
#         '4':1/3,
#         '5':1/6,
#         '6':1/9,
#     }
#     return from_for[str(i)]

def relations_values(i):
    from_for = {
        '0':9,
        '1':8,
        '2':7,
        '3':6,
        '4':5,
        '5':4,
        '6':3,
        '7':2,
        '8':1,
        '9':1/2,
        '10':1/3,
        '11':1/4,
        '12':1/5,
        '13':1/6,
        '14':1/7,
        '15':1/8,
        '16':1/9,
    }
    return from_for[str(i)]

from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponse
import json

@csrf_exempt
def AjaxPostView(request):
    objectDict = json.loads(request.body.decode("utf-8"))
    print
    items = GroupRelationship.objects.filter(group=objectDict['object_id'])
    aux = []
    for el in items:
        aux.append(el.criterion.name)
    values =  processPost(objectDict, aux)
    return HttpResponse(values)

def processPost(arg, criterion_list):
    print(criterion_list)
    response_array = []
    matrix_length = int(arg['qtd'])
    len_relations = int(arg['len_relations'])
    matrix_a = np.identity(matrix_length)
    matrix_b = np.identity(matrix_length)

    for integer in range(len_relations):
        response_array.append(relations_values(int(arg['range_'+ str(integer)])))
    print(response_array)

    stepper_control = 0
    for line in range(matrix_length-1):
        boolean_control = False
        for column in range(matrix_length-1):
            if matrix_a[line][column] == 1 and not boolean_control:
                boolean_control = True
            if boolean_control:
                matrix_a[line][column+1] = response_array[stepper_control]
                stepper_control += 1

    for line in range(matrix_length):
        for column in range(matrix_length):
            if  column < line:
                matrix_a[line][column] = 1/matrix_a[column][line]

    for line in range(matrix_length):
        for column in range(matrix_length):
            matrix_b[line][column] = matrix_a[line][column]/matrix_a.sum(axis=0)[column]

    vector_w = np.mean(matrix_b, axis=1)
    vector_c = matrix_a.dot(vector_w)

    new_object = {}
    i = 0
    for el in criterion_list:
        new_object.update({el:vector_w[i]})
        i += 1

    context = {}
    context.update({'prioridades': new_object })
    print(new_object)


    aux = []
    for i in range(len(vector_c)):
        aux.append(vector_c[i] / vector_w[i])

    lambda_max = np.mean(aux)
    CI = (lambda_max - matrix_length) / (matrix_length-1)
    incosistency = round(CI/random_index_reference(matrix_length) * 100, 2)
    context.update({'inconsistencia': incosistency })
    return JsonResponse(context, safe=False)
    

def random_index_reference(n):
    auxiliar_array = [0,0,0.58,0.9,1.12,1.24,1.32,1.41,1.45,1.49,1.51,1.48,1.56,1.57,1.59]
    return auxiliar_array[n-1]



class GroupsCreate(CreateView):
    model = Groups
    fields = ['name']
    success_url = reverse_lazy('groups:list')

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)
    
    def form_valid(self, form):
        form.instance.created_by = self.request.user
        return super().form_valid(form)

from django.http import JsonResponse

class RelationshipCreate(CreateView):
    model = GroupRelationship
    fields = ['group', 'criterion']
    returId = None

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)
    
    def form_valid(self, form):
        self.returId = form.cleaned_data['group'].id
        return super().form_valid(form)

    def get_success_url(self):
        try:
            group = Groups.objects.get(pk=self.returId)
            url = group.get_absolute_url()
        except AttributeError:
            raise ImproperlyConfigured(
                "No URL to redirect to.  Either provide matrix_a url or define"
                " matrix_a get_absolute_url method on the Model.")
        return url

    def get_initial(self, **kwargs):
        initial = super().get_initial()
        initial['group'] = self.kwargs['pk']
        return initial

        

class GroupsUpdate(UpdateView):
    model = Groups
    fields = ['name']
    success_url = reverse_lazy('groups:list')

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)


class GroupsDelete(DeleteView):
    model = Groups
    success_url = reverse_lazy('groups:list')

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

groups/templates/groups/excution_form.html
{% extends 'base.html' %}
{% load i18n %}
{% block content %}
<form action="" method="post" class="form-control">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save" />
</form>
{% endblock %}

groups/templates/groups/grouprelationship_form.html
{% extends 'base.html' %}
{% load i18n %}
{% block content %}
<form action="" method="post" class="form-control">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Save" />
</form>
{% endblock %}

groups/templates/groups/groups_confirm_delete.html
{% extends 'base.html' %}
{% load i18n %}
{% block content %}
<form action="" method="post">
    {% csrf_token %}
    {% trans '
Os seguintes objetos, bem como seus objetos relacionados, serão excluídos. Você tem certeza?' %}
    <input type="submit" class="btn btn-primary" value="{% trans 'Confirm deletion' %}" name="confirm_delete" />
    <a class="btn btn-primary" href="{% url 'criterion:list' %}" role="button">Cancelar</a>
</form>
{% endblock %}

groups/templates/groups/groups_detail.html
{% extends 'base.html' %}
{% load i18n %}
{% block content %}
<h1>Grupo: {{ groups.name }}</h1>

<p><strong>Nome:</strong> {{ groups.name}}</p>
<p><strong>Criado por:</strong> {{ groups.created_by }}</p>
<p><strong>Criado em:</strong> {{ groups.created_at }}</p>
<p><strong>Quantidade de Critérios :</strong> {{ groups.relations_count }}</p>
<p><strong>Questões Geradas:</strong> {{ groups.amount_questions }}</p>



<a class="btn btn-primary" href="{% url 'groups:update' groups.id %}" role="button">Editar</a><br>
<a class="btn btn-danger" href="{% url 'groups:delete' groups.id %}" role="button">Deletar</a><br>
<a class="btn btn-warning" href="{% url 'groups:relationship' groups.id %}" role="button">Adicionar Relacionamento</a><br>
<a class="btn btn-warning" href="{% url 'groups:preview' groups.id %}" role="button">Pré-Visualizar Publicação</a><br>
<a class="btn btn-warning" href="{% url 'groups:publish' groups.id %}" role="button">Publicar</a><br>
<br>
<br>
<br>


    <ul>
            {% for relations in relations_list %}
            <li>{{ relations.criterion }}</li>
            {% empty %}
            <li>Sem Relacionamentos para o Grupo Ainda.</li>
            {% endfor %}
        </ul>

{% endblock %}

groups/templates/groups/groups_form.html
{% extends 'base.html' %}
{% load i18n %}
{% block content %}
<form action="" method="post" class="form-control">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save" />
</form>
{% endblock %}

groups/templates/groups/groups_list.html
{% extends 'base.html' %}
{% load i18n %}
{% block content %}
<h1>Grupos Cadastrados</h1>
<ul>
    {% for groups in object_list %}
    <li><a href="{% url 'groups:detail' groups.id %}">{{ groups.name }}</a></li>
    {% empty %}
    <li>Sem Grupos Ainda.</li>
    {% endfor %}
</ul>


<a class="btn btn-primary" href="{% url 'groups:add' %}" role="button">Novo Grupo</a>


{% endblock %}

groups/templates/groups/groups_publish.html
{% extends 'base.html' %}
{% load i18n %}
{% block content %}
{% load static %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.js"
    integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU=" crossorigin="anonymous"></script>
<style>
    .slidecontainer {
        width: 100%;
        /* Width of the outside container */
    }

    .slider {
        -webkit-appearance: none;
        /* Override default CSS styles */
        appearance: none;
        width: 100%;
        /* Full-width */
        height: 25px;
        /* Specified height */
        background: #000000;
        /* Grey background */
        outline: none;
        /* Remove outline */
        opacity: 0.3;
        height: 2px;
        /* Set transparency (for mouse-over effects on hover) */
        -webkit-transition: .2s;
        /* 0.2 seconds transition on hover */
        transition: opacity .2s;
    }

    .slider:hover {
        opacity: 1;
        /* Fully shown on mouse-over */
    }

    .slider::-webkit-slider-thumb {
        -webkit-appearance: none;
        /* Override default look */
        appearance: none;
        width: 25px;
        /* Set a specific slider handle width */
        height: 25px;
        /* Slider handle height */
        background: rgb(21, 103, 255);
        border-radius: 12px;
        /* Green background */
        cursor: pointer;
        /* Cursor on hover */
    }

    .slider::-moz-range-thumb {
        width: 25px;
        /* Set a specific slider handle width */
        height: 25px;
        /* Slider handle height */
        background: #4CAF50;
        /* Green background */
        cursor: pointer;
        /* Cursor on hover */
    }


    @media (min-height: 320px) {
        .ui.footer.form-page {
            position: absolute;
            bottom: 0;
            width: 100%;
        }

    }
</style>
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@9"></script>
<script src="https://code.highcharts.com/highcharts.js"></script>
<script src="https://code.highcharts.com/modules/data.js"></script>
<script src="https://code.highcharts.com/modules/accessibility.js"></script>


<script src="{% static 'js/pub_form.js' %}"></script>

<script type="text/javascript">
    console.log(window.screen.availHeight,
        window.screen.availWidth)

    if (window.screen.availWidth > 700) {

        window.onscroll = function () {

            var height = document.body.clientHeight;

            var a = $('#main').height()
            var b = $('#cont').height()

            if (window.pageYOffset < (a - b)) {
                // if (true){
                console.log('andou', window.pageYOffset)

                document.getElementById('cont').style.top = window.pageYOffset + 'px';
            }

        };
    }

</script>
<br>
<div class="ui container">
    <div class="ui stackable two column grid">
        <div class="row">
            <div class="main column" id="main">
                <div class="ui segment">
                    <a class="ui blue ribbon label">Formulário</a>
                    <p></p>
                    <form action="" method="post" class="form-control" id="my_form">
                        {% csrf_token %}
                        <input type="hidden" id="len_relations" value="{{len_relations}}" name='len_relations'>
                        <input type="hidden" value="{{len_criterios}}" name='qtd'>
                        <input type="hidden" value="{{id}}" name='object_id'>
                        {% for relations in relations_list %}
                        <div style="padding: 10px; border: 1px solid #cacaca;">
                            <div className="ui label floated left pointing" id="projectsMenuCounter">
                                <div style="float:left;" className="ui active inline loader inverted">
                                    <strong>{{ relations.0 }}</strong>
                                </div>
                                <div style="float:right;" className="ui active inline loader inverted">
                                    <strong>{{ relations.1 }}</strong>
                                </div>
                            </div>
                            <br>
                            <div class="slidecontainer border border-success">
                                <div style="display: flex; justify-content: space-around;">
                                    <div>9</div>
                                    <div>8</div>
                                    <div>7</div>
                                    <div>6</div>
                                    <div>5</div>
                                    <div>4</div>
                                    <div>3</div>
                                    <div>2</div>
                                    <div>1</div>
                                    <div>2</div>
                                    <div>3</div>
                                    <div>4</div>
                                    <div>5</div>
                                    <div>6</div>
                                    <div>7</div>
                                    <div>8</div>
                                    <div>9</div>
                                </div>
                                <input type="range" name="range_{{ forloop.counter0 }}" min="0" max="16" class="slider"
                                    data-name1="{{ relations.0 }}" data-name2="{{ relations.1 }}"
                                    id="range_{{ forloop.counter0 }}">
                                <p style="padding-top:10px">R: <span id="span_{{ forloop.counter0 }}"></span></p>
                            </div>
                        </div>
                        <br>
                        {% empty %}
                        <li>Sem Relacionamentos para o Grupo Ainda.</li>
                        {% endfor %}
                    </form>
                    <p></p>
                </div>
            </div>
            <div class="column">
                <div class="ui sticky segments" id='cont'>

                    <div class="ui segment">
                        <a class="ui orange right ribbon label">Preferências</a>
                        <div id="container"></div>
                        <br>
                        <div style="text-align: center;">
                            <div id='btn-red'>
                                <h4 class="ui horizontal divider header">
                                    <i class="tag icon"></i>
                                    Resultados
                                </h4>
                                <div class="ui labeled button" tabindex="0">
                                    <div class="ui red button">
                                        <i class="hand point down icon"></i> Inconsistência
                                    </div>
                                    <a class="ui basic red left pointing label">
                                        <span id="ci1"></span>%
                                    </a>
                                </div>
                            </div>

                            <div id='btn-green'>
                                <h4 class="ui horizontal divider header">
                                    <i class="tag icon"></i>
                                    Resultados
                                </h4>
                                <div class="ui labeled button" tabindex="0">
                                    <div class="ui green button">
                                        <i class="hand point up icon"></i> Inconsistência
                                    </div>
                                    <a class="ui basic green left pointing label">
                                        <span id="ci2"></span>%
                                    </a>
                                </div>
                            </div>
                        </div>
                        <br>
                        <div id="btn" class="right item">
                            <h4 class="ui horizontal divider header">
                                <i class="tag icon"></i>
                                Submeter
                            </h4>
                            <a class="ui black bottom attached button" onclick="fakeSubmit()"><i
                                    class="icon play"></i>Submeter</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <br>
</div>

{% endblock %}