formAhp/urls.py
from django.contrib import admin
from django.urls import path, include
from groups.views import AjaxPostView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # ... the rest of your URLconf goes here ...
    path('admin/', admin.site.urls),
    path('auth/', include('django.contrib.auth.urls')),
    path('', include('criterion.urls', namespace='home')),
    path('criterion/', include('criterion.urls', namespace='criterion')),
    path('user/', include('user.urls', namespace='user')),
    path('groups/', include('groups.urls', namespace='groups')),
    path('research/', include('research.urls', namespace='research')),
    path('ajax-post', AjaxPostView, name='ajax-post'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)







# auth/login/ [name='login']
# auth/logout/ [name='logout']
# auth/password_change/ [name='password_change']
# auth/password_change/done/ [name='password_change_done']
# auth/password_reset/ [name='password_reset']
# auth/password_reset/done/ [name='password_reset_done']
# auth/reset/<uidb64>/<token>/ [name='password_reset_confirm']
# auth/reset/done/ [name='password_reset_complete']

user/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views


app_name = 'user'


urlpatterns = [
    path('', views.UserList.as_view(), name='list'),
    path('add', views.UserCreate.as_view(), name='add'),
    path('detail/<str:pk>/', views.UserDetail.as_view(), name='detail'),
    path('update/<str:pk>/', views.UserUpdate.as_view(), name='update'),
    path('delete/<str:pk>', views.UserDelete.as_view(), name='delete'),
]

user/models.py
from django.contrib.auth.models import AbstractUser
from django.urls import reverse
from django.db import models
import datetime
import uuid



class BaseModel(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)

    class Meta:
        abstract = True


class User(AbstractUser, BaseModel):
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']
    TYPE_CHOICES = (
        ('admin', 'Administrador'),
        ('encarregado', 'Encarregado'),
        ('operario', 'Operário'),
        ('gerente', 'Gerente'),
    )
    occupation = models.CharField(
        max_length=20, 
        choices=TYPE_CHOICES, 
        default=TYPE_CHOICES[0][0], 
        verbose_name='Qual o seu perfil?'
    )
    company = models.CharField(
        max_length=20, 
        verbose_name='Empresa', 
        null=True, 
        blank=True
    )
    email = models.EmailField(unique=True)
    joined = models.DateField(default=datetime.date.today)
    
    def get_absolute_url(self):
        return reverse('detail', kwargs={'pk': self.pk})

user/forms.py
from django.contrib.auth.forms import UserCreationForm
from user.models import User

class UserCreateForm(UserCreationForm):

    class Meta:
        model = User
        fields = ('email', 'occupation' , 'company', )

user/views.py
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.views.generic import DetailView, ListView
from django.urls import reverse_lazy
from django.http import Http404

from user.models import User
from user.forms import UserCreateForm

class UserList(ListView):
    model = User


class UserDetail(DetailView):
    model = User


class UserCreate(CreateView):
    model = User
    form_class = UserCreateForm    
    success_url = reverse_lazy('user:list')


class UserUpdate(UpdateView):
    model = User
    fields = ['email', 'username']
    success_url = reverse_lazy('user:list')


class UserDelete(DeleteView):
    model = User
    success_url = reverse_lazy('user:list')


    

    
    

user/templates/user/user_confirm_delete.html
{% extends 'base.html' %}
{% load i18n %}
{% block content %}
<form action="" method="post">
    {% csrf_token %}
    {% trans '
Os seguintes objetos, bem como seus objetos relacionados, serão excluídos. Você tem certeza?' %}
    <input type="submit" class="btn btn-primary" value="{% trans 'Confirm deletion' %}" name="confirm_delete" />
    <a class="btn btn-primary" href="{% url 'user:list' %}" role="button">Cancelar</a>
</form>
{% endblock %}

user/templates/user/user_detail.html
{% extends 'base.html' %}
{% load i18n %}
{% block content %}

<h1>Usuário: {{ user.email }}</h1>

<p><strong>Nome:</strong> <a href="">{{ user.email}}</a></p>
<p><strong>Nome:</strong> {{ user.email }}</p>
<p><strong>Nome:</strong> {{ user.email }}</p>
<p><strong>Nome:</strong> {{ user.email }}</p>



<a class="btn btn-primary" href="{% url 'user:update' user.id %}" role="button">Editar</a> <br><br>
<a class="btn btn-danger" href="{% url 'user:delete' user.id %}" role="button">Deletar</a>
{% endblock %}

user/templates/user/user_form.html
{% extends 'base.html' %}
{% load i18n %}
{% block content %}
<h2>Registrar-se</h2>
<form method="post">
  {% csrf_token %}
  {% for field in form %}
    <p>
      {{ field.label_tag }}<br>
      {{ field }}
      <!-- {% if field.help_text %}
        <small style="color: grey">{{ field.help_text }}</small>
      {% endif %} -->
      {% for error in field.errors %}
        <p style="color: red">{{ error }}</p>
      {% endfor %}
    </p>
  {% endfor %}
  <button type="submit">Sign up</button>
</form>
{% endblock %}

user/templates/user/user_list.html
{% extends 'base.html' %}
{% load i18n %}
{% block content %}
<h1>Usuários Cadastrados</h1>
<ul>
    {% for user in object_list %}
    <li><a href="{% url 'user:detail' user.id %}">{{ user.email }}</a></li>
    {% empty %}
    <li>Sem usuários ainda.</li>
    {% endfor %}
</ul>


<a class="btn btn-primary" href="{% url 'user:add' %}" role="button">Novo Usuário</a>


{% endblock %}