formAhp/urls.py
from django.contrib import admin
from django.urls import path, include
from groups.views import AjaxPostView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # ... the rest of your URLconf goes here ...
    path('admin/', admin.site.urls),
    path('auth/', include('django.contrib.auth.urls')),
    path('', include('criterion.urls', namespace='home')),
    path('criterion/', include('criterion.urls', namespace='criterion')),
    path('user/', include('user.urls', namespace='user')),
    path('groups/', include('groups.urls', namespace='groups')),
    path('research/', include('research.urls', namespace='research')),
    path('ajax-post', AjaxPostView, name='ajax-post'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)







# auth/login/ [name='login']
# auth/logout/ [name='logout']
# auth/password_change/ [name='password_change']
# auth/password_change/done/ [name='password_change_done']
# auth/password_reset/ [name='password_reset']
# auth/password_reset/done/ [name='password_reset_done']
# auth/reset/<uidb64>/<token>/ [name='password_reset_confirm']
# auth/reset/done/ [name='password_reset_complete']

user/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views


app_name = 'user'


urlpatterns = [
    path('', views.UserList.as_view(), name='list'),
    path('add', views.UserCreate.as_view(), name='add'),
    path('detail/<str:pk>/', views.UserDetail.as_view(), name='detail'),
    path('update/<str:pk>/', views.UserUpdate.as_view(), name='update'),
    path('delete/<str:pk>', views.UserDelete.as_view(), name='delete'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <!-- Standard Meta -->
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">

  <!-- Site Properties -->
  <title>AHP WEB</title>
  <link rel="stylesheet" type="text/css" href="{% static 'dist/components/reset.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'dist/components/site.css' %}">

  <link rel="stylesheet" type="text/css" href="{% static 'dist/components/container.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'dist/components/grid.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'dist/components/header.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'dist/components/image.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'dist/components/menu.css' %}">

  <link rel="stylesheet" type="text/css" href="{% static 'dist/components/divider.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'dist/components/dropdown.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'dist/components/segment.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'dist/components/button.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'dist/components/list.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'dist/components/icon.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'dist/components/sidebar.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'dist/components/transition.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'dist/components/range.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'dist/components/form.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'dist/components/label.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'dist/components/input.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'dist/components/message.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'dist/components/table.css' %}">




  <style type="text/css' %}">

    .hidden.menu {
      display: none;
    }

    .masthead.segment {
      min-height: 700px;
      padding: 1em 0em;
    }
    .masthead .logo.item img {
      margin-right: 1em;
    }
    .masthead .ui.menu .ui.button {
      margin-left: 0.5em;
    }
    .masthead h1.ui.header {
      margin-top: 3em;
      margin-bottom: 0em;
      font-size: 4em;
      font-weight: normal;
    }
    .masthead h2 {
      font-size: 1.7em;
      font-weight: normal;
    }

    .ui.vertical.stripe {
      padding: 8em 0em;
    }
    .ui.vertical.stripe h3 {
      font-size: 2em;
    }
    .ui.vertical.stripe .button + h3,
    .ui.vertical.stripe p + h3 {
      margin-top: 3em;
    }
    .ui.vertical.stripe .floated.image {
      clear: both;
    }
    .ui.vertical.stripe p {
      font-size: 1.33em;
    }
    .ui.vertical.stripe .horizontal.divider {
      margin: 3em 0em;
    }

    .quote.stripe.segment {
      padding: 0em;
    }
    .quote.stripe.segment .grid .column {
      padding-top: 5em;
      padding-bottom: 5em;
    }

    .footer.segment {
      padding: 5em 0em;
    }

    .secondary.pointing.menu .toc.item {
      display: none;
    }

    @media only screen and (max-width: 700px) {
      .ui.fixed.menu {
        display: none !important;
      }
      .secondary.pointing.menu .item,
      .secondary.pointing.menu .menu {
        display: none;
      }
      .secondary.pointing.menu .toc.item {
        display: block;
      }
      .masthead.segment {
        min-height: 350px;
      }
      .masthead h1.ui.header {
        font-size: 2em;
        margin-top: 1.5em;
      }
      .masthead h2 {
        margin-top: 0.5em;
        font-size: 1.5em;
      }
    }
 
    
  </style>

  <script src="{% static  'assets/library/jquery.min.js' %}"></script>
  <script src="{% static 'dist/components/visibility.js' %}"></script>
  <script src="{% static 'dist/components/sidebar.js' %}"></script>
  <script src="{% static 'dist/components/transition.js' %}"></script>
  <script src="{% static 'dist/components/range.js' %}"></script>
  <script src="{% static 'dist/components/form.js' %}"></script>
  <!-- <script>
  $(document)
    .ready(function() {

      // fix menu when passed
      $('.masthead')
        .visibility({
          once: false,
          onBottomPassed: function() {
            $('.fixed.menu').transition('fade in');
          },
          onBottomPassedReverse: function() {
            $('.fixed.menu').transition('fade out');
          }
        })
      ;

      // create sidebar and attach to menu open
      $('.ui.sidebar')
        .sidebar('attach events', '.toc.item')
      ;

    })
  ;
  </script> -->
</head>
<body>

<!-- Following Menu -->
<div class="ui large top fixed hidden menu">
  <div class="ui container">
    <a class="active item">Home</a>
    <a class="item" href="{% url 'criterion:list' %}">Critérios</a>
    <a class="item" href="{% url 'groups:list' %}">Formulários</a>
    <a class="item" href="{% url 'research:list' %}">Pesquisas</a>
    <div class="right menu">
      <div class="item">
        <a class="ui button" href="/auth/logout">Log out</a>
      </div>
      <div class="item">
        <a class="ui primary button" href="{% url 'user:add' %}">Sign Up</a>
      </div>
    </div>
  </div>
</div>

<!-- Sidebar Menu -->
<div class="ui vertical inverted sidebar menu">
  <a class="active item">Home</a>
  <a class="item">Critérios</a>
  <a class="item">Formulários</a>
  <a class="item">Pesquisas</a>
  <a class="item">Login</a>
  <a class="item">Signup</a>
</div>




<br><br><br>

  {% block content %}
  {% endblock %}



  <!-- <div class="ui vertical stripe quote segment">
    <div class="ui equal width stackable internally celled grid">
      <div class="center aligned row">
        <div class="column">
          <h3>"What a Company"</h3>
          <p>That is what they all say about us</p>
        </div>
        <div class="column">
          <h3>"I shouldn't have gone with their competitor."</h3>
          <p>
            <img src="{% static  'assets/images/avatar/nan.jpg' %}" class="ui avatar image"> <b>Nan</b> Chief Fun Officer Acme Toys
          </p>
        </div>
      </div>
    </div>
  </div>

  <div class="ui vertical stripe segment">
    <div class="ui text container">
      <h3 class="ui header">Breaking The Grid, Grabs Your Attention</h3>
      <p>Instead of focusing on content creation and hard work, we have learned how to master the art of doing nothing by providing massive amounts of whitespace and generic content that can seem massive, monolithic and worth your attention.</p>
      <a class="ui large button">Read More</a>
      <h4 class="ui horizontal header divider">
        <a href="#">Case Studies</a>
      </h4>
      <h3 class="ui header">Did We Tell You About Our Bananas?</h3>
      <p>Yes I know you probably disregarded the earlier boasts as non-sequitur filler content, but its really true. It took years of gene splicing and combinatory DNA research, but our bananas can really dance.</p>
      <a class="ui large button">I'm Still Quite Interested</a>
    </div>
  </div> -->




</body>

</html>

templates/base2.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <!-- Standard Meta -->
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">

  <!-- Site Properties -->
  <title>AHP-WEB</title>
  <link rel="stylesheet" type="text/css" href="{% static 'dist/components/reset.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'dist/components/site.css' %}">

  <link rel="stylesheet" type="text/css" href="{% static 'dist/components/container.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'dist/components/grid.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'dist/components/header.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'dist/components/image.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'dist/components/menu.css' %}">

  <link rel="stylesheet" type="text/css" href="{% static 'dist/components/divider.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'dist/components/dropdown.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'dist/components/segment.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'dist/components/button.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'dist/components/list.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'dist/components/icon.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'dist/components/sidebar.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'dist/components/transition.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'dist/components/range.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'dist/components/form.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'dist/components/label.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'dist/components/input.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'dist/components/message.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'dist/components/menu.css' %}">

  
  <script>
  $(document).ready(function(){
    $('[data-toggle="tooltip"]').tooltip();   
  });
  </script>



  <style type="text/css' %}">

    .hidden.menu {
      display: none;
    }

    .masthead.segment {
      min-height: 700px;
      padding: 1em 0em;
    }
    .masthead .logo.item img {
      margin-right: 1em;
    }
    .masthead .ui.menu .ui.button {
      margin-left: 0.5em;
    }
    .masthead h1.ui.header {
      margin-top: 3em;
      margin-bottom: 0em;
      font-size: 4em;
      font-weight: normal;
    }
    .masthead h2 {
      font-size: 1.7em;
      font-weight: normal;
    }

    .ui.vertical.stripe {
      padding: 8em 0em;
    }
    .ui.vertical.stripe h3 {
      font-size: 2em;
    }
    .ui.vertical.stripe .button + h3,
    .ui.vertical.stripe p + h3 {
      margin-top: 3em;
    }
    .ui.vertical.stripe .floated.image {
      clear: both;
    }
    .ui.vertical.stripe p {
      font-size: 1.33em;
    }
    .ui.vertical.stripe .horizontal.divider {
      margin: 3em 0em;
    }

    .quote.stripe.segment {
      padding: 0em;
    }
    .quote.stripe.segment .grid .column {
      padding-top: 5em;
      padding-bottom: 5em;
    }

    .footer.segment {
      padding: 5em 0em;
    }

    .secondary.pointing.menu .toc.item {
      display: none;
    }

    @media only screen and (max-width: 700px) {
      .ui.fixed.menu {
        display: none !important;
      }
      .secondary.pointing.menu .item,
      .secondary.pointing.menu .menu {
        display: none;
      }
      .secondary.pointing.menu .toc.item {
        display: block;
      }
      .masthead.segment {
        min-height: 350px;
      }
      .masthead h1.ui.header {
        font-size: 2em;
        margin-top: 1.5em;
      }
      .masthead h2 {
        margin-top: 0.5em;
        font-size: 1.5em;
      }
    }

    
    .ui.footer { 
      position: absolute;
      bottom: 0;
      width: 100%;
    }

  </style>

  <script src="{% static  'assets/library/jquery.min.js' %}"></script>
  <script src="{% static 'dist/components/visibility.js' %}"></script>
  <script src="{% static 'dist/components/sidebar.js' %}"></script>
  <script src="{% static 'dist/components/transition.js' %}"></script>
  <script src="{% static 'dist/components/range.js' %}"></script>
  <script src="{% static 'dist/components/form.js' %}"></script>
  <!-- <script>
  $(document)
    .ready(function() {

      // fix menu when passed
      $('.masthead')
        .visibility({
          once: false,
          onBottomPassed: function() {
            $('.fixed.menu').transition('fade in');
          },
          onBottomPassedReverse: function() {
            $('.fixed.menu').transition('fade out');
          }
        })
      ;

      // create sidebar and attach to menu open
      $('.ui.sidebar')
        .sidebar('attach events', '.toc.item')
      ;

    })
  ;
  </script> -->
</head>
<body>
   {% block textHeader %}
                {% endblock %}
        <!-- <div class="ui container">

    <div class="ui sticky secondary segment">
        <p>
               
      </div>
      </div> -->
<!-- <div class="ui large top fixed hidden menu">
  <div class="ui container">
    <a class="active item">Home</a>
    <a class="item" href="{% url 'criterion:list' %}">Critérios</a>
    <a class="item" href="{% url 'groups:list' %}">Formulários</a>
    <a class="item" href="{% url 'research:list' %}">Pesquisas</a>
    <div class="right menu">
      <div class="item">
        <a class="ui button" href="/auth/logout">Log out</a>
      </div>
      <div class="item">
        <a class="ui primary button" href="{% url 'user:add' %}">Sign Up</a>
      </div>
    </div>
  </div>
</div>

<div class="ui vertical inverted sidebar menu">
  <a class="active item">Home</a>
  <a class="item">Critérios</a>
  <a class="item">Formulários</a>
  <a class="item">Pesquisas</a>
  <a class="item">Login</a>
  <a class="item">Signup</a>
</div> -->





  {% block content %}
  {% endblock %}



  <!-- <div class="ui vertical stripe quote segment">
    <div class="ui equal width stackable internally celled grid">
      <div class="center aligned row">
        <div class="column">
          <h3>"What a Company"</h3>
          <p>That is what they all say about us</p>
        </div>
        <div class="column">
          <h3>"I shouldn't have gone with their competitor."</h3>
          <p>
            <img src="{% static  'assets/images/avatar/nan.jpg' %}" class="ui avatar image"> <b>Nan</b> Chief Fun Officer Acme Toys
          </p>
        </div>
      </div>
    </div>
  </div>

  <div class="ui vertical stripe segment">
    <div class="ui text container">
      <h3 class="ui header">Breaking The Grid, Grabs Your Attention</h3>
      <p>Instead of focusing on content creation and hard work, we have learned how to master the art of doing nothing by providing massive amounts of whitespace and generic content that can seem massive, monolithic and worth your attention.</p>
      <a class="ui large button">Read More</a>
      <h4 class="ui horizontal header divider">
        <a href="#">Case Studies</a>
      </h4>
      <h3 class="ui header">Did We Tell You About Our Bananas?</h3>
      <p>Yes I know you probably disregarded the earlier boasts as non-sequitur filler content, but its really true. It took years of gene splicing and combinatory DNA research, but our bananas can really dance.</p>
      <a class="ui large button">I'm Still Quite Interested</a>
    </div>
  </div> -->

  </div>

</body>

</html>

templates/base3.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <!-- Standard Meta -->
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">

  <!-- Site Properties -->
  <title>Homepage - Semantic</title>
  <link rel="stylesheet" type="text/css" href="{% static 'dist/components/reset.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'dist/components/site.css' %}">

  <link rel="stylesheet" type="text/css" href="{% static 'dist/components/container.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'dist/components/grid.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'dist/components/header.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'dist/components/image.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'dist/components/menu.css' %}">

  <link rel="stylesheet" type="text/css" href="{% static 'dist/components/divider.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'dist/components/dropdown.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'dist/components/segment.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'dist/components/button.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'dist/components/list.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'dist/components/icon.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'dist/components/sidebar.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'dist/components/transition.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'dist/components/range.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'dist/components/form.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'dist/components/label.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'dist/components/input.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'dist/components/message.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'dist/components/menu.css' %}">




  <style type="text/css' %}">

    .hidden.menu {
      display: none;
    }

    .masthead.segment {
      min-height: 700px;
      padding: 1em 0em;
    }
    .masthead .logo.item img {
      margin-right: 1em;
    }
    .masthead .ui.menu .ui.button {
      margin-left: 0.5em;
    }
    .masthead h1.ui.header {
      margin-top: 3em;
      margin-bottom: 0em;
      font-size: 4em;
      font-weight: normal;
    }
    .masthead h2 {
      font-size: 1.7em;
      font-weight: normal;
    }

    .ui.vertical.stripe {
      padding: 8em 0em;
    }
    .ui.vertical.stripe h3 {
      font-size: 2em;
    }
    .ui.vertical.stripe .button + h3,
    .ui.vertical.stripe p + h3 {
      margin-top: 3em;
    }
    .ui.vertical.stripe .floated.image {
      clear: both;
    }
    .ui.vertical.stripe p {
      font-size: 1.33em;
    }
    .ui.vertical.stripe .horizontal.divider {
      margin: 3em 0em;
    }

    .quote.stripe.segment {
      padding: 0em;
    }
    .quote.stripe.segment .grid .column {
      padding-top: 5em;
      padding-bottom: 5em;
    }

    .footer.segment {
      padding: 5em 0em;
    }

    .secondary.pointing.menu .toc.item {
      display: none;
    }

    @media only screen and (max-width: 700px) {
      .ui.fixed.menu {
        display: none !important;
      }
      .secondary.pointing.menu .item,
      .secondary.pointing.menu .menu {
        display: none;
      }
      .secondary.pointing.menu .toc.item {
        display: block;
      }
      .masthead.segment {
        min-height: 350px;
      }
      .masthead h1.ui.header {
        font-size: 2em;
        margin-top: 1.5em;
      }
      .masthead h2 {
        margin-top: 0.5em;
        font-size: 1.5em;
      }
    }

    
    .ui.footer { 
      position: absolute;
      bottom: 0;
      width: 100%;
    }

  </style>

  <script src="{% static  'assets/library/jquery.min.js' %}"></script>
  <script src="{% static 'dist/components/visibility.js' %}"></script>
  <script src="{% static 'dist/components/sidebar.js' %}"></script>
  <script src="{% static 'dist/components/transition.js' %}"></script>
  <script src="{% static 'dist/components/range.js' %}"></script>
  <script src="{% static 'dist/components/form.js' %}"></script>
  <!-- <script>
  $(document)
    .ready(function() {

      // fix menu when passed
      $('.masthead')
        .visibility({
          once: false,
          onBottomPassed: function() {
            $('.fixed.menu').transition('fade in');
          },
          onBottomPassedReverse: function() {
            $('.fixed.menu').transition('fade out');
          }
        })
      ;

      // create sidebar and attach to menu open
      $('.ui.sidebar')
        .sidebar('attach events', '.toc.item')
      ;

    })
  ;
  </script> -->
</head>
<body>

        <!-- <div class="ui container">

    <div class="ui sticky secondary segment">
        <p>
               
      </div>
      </div> -->
<!-- <div class="ui large top fixed hidden menu">
  <div class="ui container">
    <a class="active item">Home</a>
    <a class="item" href="{% url 'criterion:list' %}">Critérios</a>
    <a class="item" href="{% url 'groups:list' %}">Formulários</a>
    <a class="item" href="{% url 'research:list' %}">Pesquisas</a>
    <div class="right menu">
      <div class="item">
        <a class="ui button" href="/auth/logout">Log out</a>
      </div>
      <div class="item">
        <a class="ui primary button" href="{% url 'user:add' %}">Sign Up</a>
      </div>
    </div>
  </div>
</div>

<div class="ui vertical inverted sidebar menu">
  <a class="active item">Home</a>
  <a class="item">Critérios</a>
  <a class="item">Formulários</a>
  <a class="item">Pesquisas</a>
  <a class="item">Login</a>
  <a class="item">Signup</a>
</div> -->





  {% block content %}
  {% endblock %}



  <!-- <div class="ui vertical stripe quote segment">
    <div class="ui equal width stackable internally celled grid">
      <div class="center aligned row">
        <div class="column">
          <h3>"What a Company"</h3>
          <p>That is what they all say about us</p>
        </div>
        <div class="column">
          <h3>"I shouldn't have gone with their competitor."</h3>
          <p>
            <img src="{% static  'assets/images/avatar/nan.jpg' %}" class="ui avatar image"> <b>Nan</b> Chief Fun Officer Acme Toys
          </p>
        </div>
      </div>
    </div>
  </div>

  <div class="ui vertical stripe segment">
    <div class="ui text container">
      <h3 class="ui header">Breaking The Grid, Grabs Your Attention</h3>
      <p>Instead of focusing on content creation and hard work, we have learned how to master the art of doing nothing by providing massive amounts of whitespace and generic content that can seem massive, monolithic and worth your attention.</p>
      <a class="ui large button">Read More</a>
      <h4 class="ui horizontal header divider">
        <a href="#">Case Studies</a>
      </h4>
      <h3 class="ui header">Did We Tell You About Our Bananas?</h3>
      <p>Yes I know you probably disregarded the earlier boasts as non-sequitur filler content, but its really true. It took years of gene splicing and combinatory DNA research, but our bananas can really dance.</p>
      <a class="ui large button">I'm Still Quite Interested</a>
    </div>
  </div> -->


  <!-- <div class="ui inverted vertical footer segment">
    <div class="ui container">
      <div class="ui stackable inverted divided equal height stackable grid">
        <div class="three wide column">
          <h4 class="ui inverted header">About</h4>
          <div class="ui inverted link list">
            <a href="#" class="item">Sitemap</a>
            <a href="#" class="item">Contact Us</a>
            <a href="#" class="item">Religious Ceremonies</a>
            <a href="#" class="item">Gazebo Plans</a>
          </div>
        </div>
        <div class="three wide column">
          <h4 class="ui inverted header">Services</h4>
          <div class="ui inverted link list">
            <a href="#" class="item">Banana Pre-Order</a>
            <a href="#" class="item">DNA FAQ</a>
            <a href="#" class="item">How To Access</a>
            <a href="#" class="item">Favorite X-Men</a>
          </div>
        </div>
        <div class="seven wide column">
          <h4 class="ui inverted header">Footer Header</h4>
          <p>Extra space for a call to action inside the footer that could help re-engage users.</p>
        </div>
      </div>
    </div>
  </div>
</div> -->

</body>

</html>