criterion/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views


app_name = 'criterion'


urlpatterns = [
    path('', views.CriterionList.as_view(), name='list'),
    path('add', views.CriterionCreate.as_view(), name='add'),
    path('detail/<str:pk>/', views.CriterionDetail.as_view(), name='detail'),
    path('update/<str:pk>/', views.CriterionUpdate.as_view(), name='update'),
    path('delete/<str:pk>', views.CriterionDelete.as_view(), name='delete'),
]

formAhp/urls.py
from django.contrib import admin
from django.urls import path, include
from groups.views import AjaxPostView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # ... the rest of your URLconf goes here ...
    path('admin/', admin.site.urls),
    path('auth/', include('django.contrib.auth.urls')),
    path('', include('criterion.urls', namespace='home')),
    path('criterion/', include('criterion.urls', namespace='criterion')),
    path('user/', include('user.urls', namespace='user')),
    path('groups/', include('groups.urls', namespace='groups')),
    path('research/', include('research.urls', namespace='research')),
    path('ajax-post', AjaxPostView, name='ajax-post'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)







# auth/login/ [name='login']
# auth/logout/ [name='logout']
# auth/password_change/ [name='password_change']
# auth/password_change/done/ [name='password_change_done']
# auth/password_reset/ [name='password_reset']
# auth/password_reset/done/ [name='password_reset_done']
# auth/reset/<uidb64>/<token>/ [name='password_reset_confirm']
# auth/reset/done/ [name='password_reset_complete']

user/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views


app_name = 'user'


urlpatterns = [
    path('', views.UserList.as_view(), name='list'),
    path('add', views.UserCreate.as_view(), name='add'),
    path('detail/<str:pk>/', views.UserDetail.as_view(), name='detail'),
    path('update/<str:pk>/', views.UserUpdate.as_view(), name='update'),
    path('delete/<str:pk>', views.UserDelete.as_view(), name='delete'),
]

criterion/models.py
from django.utils.translation import ugettext_lazy as _
from django.db import models
from django.urls import reverse
import uuid



class BaseModel(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)

    class Meta:
        abstract = True

class Criterion(BaseModel):
    name = models.CharField(max_length=200)
    created_by = models.ForeignKey(
        'user.User', 
        on_delete=models.PROTECT, 
        verbose_name=_("Criado por"),
        null=True,
        blank=True
        )
    created_at = models.DateTimeField(auto_now_add=True,  null=True)
    updated_at = models.DateTimeField(auto_now=True)
    def get_absolute_url(self):
        return reverse('criterion-detail', kwargs={'pk': self.pk})
    
    def __str__(self):
        return self.name

criterion/views.py
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.contrib.auth.decorators import login_required
from django.views.generic import DetailView, ListView
from django.utils.decorators import method_decorator
from django.urls import reverse_lazy
from django.http import Http404

from criterion.models import Criterion


from django.views.generic import TemplateView





class CriterionList(ListView):
    model = Criterion

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(CriterionList, self).dispatch(*args, **kwargs)

    def get_queryset(self):
        context = Criterion.objects.filter(created_by=self.request.user)
        return context


class CriterionDetail(DetailView):
    model = Criterion

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(CriterionDetail, self).dispatch(*args, **kwargs)


class CriterionCreate(CreateView):
    model = Criterion
    fields = ['name']
    success_url = reverse_lazy('criterion:list')

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(CriterionCreate, self).dispatch(*args, **kwargs)
    
    def form_valid(self, form):
        form.instance.created_by = self.request.user
        return super().form_valid(form)


class CriterionUpdate(UpdateView):
    model = Criterion
    fields = ['name']
    success_url = reverse_lazy('criterion:list')

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(CriterionUpdate, self).dispatch(*args, **kwargs)


class CriterionDelete(DeleteView):
    model = Criterion
    success_url = reverse_lazy('criterion:list')

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(CriterionDelete, self).dispatch(*args, **kwargs)

    

    
    

criterion/templates/criterion/criterion_confirm_delete.html
{% extends 'base.html' %}
{% load i18n %}
{% block content %}
<form action="" method="post">
    {% csrf_token %}
    {% trans '
Os seguintes objetos, bem como seus objetos relacionados, serão excluídos. Você tem certeza?' %}
    <input type="submit" class="btn btn-primary" value="{% trans 'Confirm deletion' %}" name="confirm_delete" />
    <a class="btn btn-primary" href="{% url 'criterion:list' %}" role="button">Cancelar</a>
</form>
{% endblock %}

criterion/templates/criterion/criterion_detail.html
{% extends 'base.html' %}
{% load i18n %}
{% block content %}
<h1>Critério: {{ criterion.name }}</h1>

<p><strong>Nome:</strong> {{ criterion.name}}</p>
<p><strong>Criado por:</strong> {{ criterion.created_by }}</p>
<p><strong>Criado em:</strong> {{ criterion.created_at }}</p>


<a class="btn btn-primary" href="{% url 'criterion:update' criterion.id %}" role="button">Editar</a>
<a class="btn btn-danger" href="{% url 'criterion:delete' criterion.id %}" role="button">Deletar</a>
{% endblock %}

criterion/templates/criterion/criterion_form.html
{% extends 'base.html' %}
{% load i18n %}
{% block content %}
<form action="" method="post" class="form-control">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save" />
</form>
{% endblock %}

criterion/templates/criterion/criterion_list.html
{% extends 'base.html' %}
{% load i18n %}
{% block content %}




<h1>Critérios Cadastrados</h1>

<ul>
    {% for criterion in object_list %}
    <li><a href="{% url 'criterion:detail' criterion.id %}">{{ criterion.name }}</a></li>
    {% empty %}
    <li>Nenhum critério ainda.</li>
    {% endfor %}
</ul>


<a class="btn btn-primary" href="{% url 'criterion:add' %}" role="button">Novo Critério</a>


{% endblock %}